services:
  db:
    image: postgres:15
    container_name: postgres_dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - postgresql-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  python:
    build: 
      context: .
      dockerfile: environments/container/Dockerfile
    container_name: python_dev
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./test_data:/app/test_data
    depends_on:
      db:
        condition: service_healthy
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - postgresql-network
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    networks:
      - postgresql-network
    depends_on:
      - db

networks:
  postgresql-network:
    driver: bridge
